quicksilver/Quicksilver

- Quicksilver/Resources/QSURLExtractor.py
- Quicksilver/Resources/bs4/__init__.py
- Quicksilver/Resources/bs4/builder/__init__.py
- Quicksilver/Resources/bs4/builder/_html5lib.py
- Quicksilver/Resources/bs4/builder/_htmlparser.py
- Quicksilver/Resources/bs4/builder/_lxml.py
- Quicksilver/Resources/bs4/dammit.py
- Quicksilver/Resources/bs4/diagnose.py
- Quicksilver/Resources/bs4/element.py
- Quicksilver/Resources/bs4/testing.py
- Quicksilver/Resources/bs4/tests/test_html5lib.py
- Quicksilver/Resources/bs4/tests/test_lxml.py
- Quicksilver/Resources/bs4/tests/test_soup.py
- Quicksilver/Resources/bs4/tests/test_tree.py
Nothing huge. I was writing a blog post for work on Beautiful Soup and was looking over this script, finding things I now don’t like. :smiley:
The only behavioral difference is that it now includes links to places on the same page (like `#this`). I can’t remember why they were ever skipped. Anyone?
> URL Extractor updates

- .travis.yml
- .travis_test.sh
- Quicksilver/Quicksilver Tests/Quicksilver_Tests.m
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/QuickStep Effects.xcscheme
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/QuickStep Interface.xcscheme
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Quicksilver Distribution.xcscheme
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Quicksilver.xcscheme
- Quicksilver/Tools/qsrelease
A rebuild of #1943
Basically the UI tests have been ignored via the use of an environment variable (hopefully!)
Ignore UI tests when running in Travis
> Use travis testing with QS

- Quicksilver/Code-QuickStepInterface/QSLargeTypeDisplay.m
> Allow the large type window to be mouse-selected

- Quicksilver/Code-App/QSController.m
Unless you’re the sort of person that likes answering this question once per week…
> make Quicksilver available on launch

- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
It seems like an innocent action and a useful addition, especially for trigger actions.
See #2214
> Enable Toggle Application by default

- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
I was hoping to address #578 on this branch, but that turns out to me more complicated than I thought and might have to wait. So here’s this.
> add isSierra test

- Quicksilver/Code-QuickStepCore/QSAlertManager.m
Pretty small one I ran into playing with file conflicts.
> allow alert panel to work with one button

- Quicksilver/PropertyLists/Quicksilver-Info.plist
> disable App Transport Security

- Quicksilver/SharedSupport/CHANGELOG
It's often helpful to see the release dates in the changelog.
> Add release dates to changelog

- Quicksilver/Code-QuickStepCore/QSCommand.m
- Quicksilver/SharedSupport/CHANGELOG
The oldest stash in my repo finally gets set free!
This does what I described in #1767.
The code isn’t as DRY as I’d like. I made some effort to factor out the task creation, but it’s not that easy. The task needs to know about the timer (for its cancel block) and the timer needs to know about the task (for its user info).
> add delayed commands to the task viewer

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
I'm going over old branches, and found this. It's purely aesthetic code from 2012 😉.
> Add a QSSearchSpaceBarBehavior enum

- Quicksilver/Code-QuickStepCore/QSPlugInManager.m
> fix download status count

- Quicksilver/Code-External/NDClasses/NSAppleEventDescriptor+NDCoercion.m
- Quicksilver/Code-QuickStepCore/QSAction.m
- Quicksilver/Code-QuickStepCore/QSPlugInManager.m
- Quicksilver/Code-QuickStepCore/QSPluginUpdaterWindowController.m
- Quicksilver/Code-QuickStepFoundation/NSFileManager_BLTRExtensions.m
Took a quick peek at the crashers for v4022 ("Updating       75 reports for 4022").
We still have memory corruption, but I've opened some issues for those that looked somewhat sane.
> Crashfixes for v4022

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSObjectActions.m
> add grabbed objects to history

- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.m
Also removes a few complaints from the console.
fixes #2417
> hide the 3rd pane when the interface is empty

- Quicksilver/Nibs/QSSetupAssistant.xib
> expand the label for “Shortcut:”

- Quicksilver/PropertyLists/Quicksilver-Info.plist
I don’t know that we use any others that support these messages.
Of course we’ll want to keep an eye on https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave
> Show reasons for accessing Contacts and Calendar

- Quicksilver/Code-App/QSController.m
When I made this call conditional, I apparently forgot to remove the original? Anyway…
> remove a stray Touch Bar API call

- .github/ISSUE_TEMPLATE/bug-report.md
Kinda weird that these are files in your repo. Not sure how I feel about that.
> Add issue templates

- Quicksilver/Code-QuickStepFoundation/QSSense.m
My attempt at implementing what was proposed after #2452
Have a look, and merge if it looks OK.
FYI @fwextensions
> more scoring tweaks

- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
- Quicksilver/Code-QuickStepInterface/QSObjectView.m
This should force some lingering UI things onto the main thread. These have been warnings for a while, but under Catalina, they will crash QS.
Progress toward #2497
> fix some crashes under Catalina

- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en-GB.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSCatalogPreset.name.strings
> index /System/Applications by default

- Quicksilver/Code-QuickStepCore/QSProcessMonitor.m
I wonder how long _that’s_ been broken. 🤦
> Post the notification required for the “Application Quit” event trigger

- .github/workflows/release.yml
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
uploaded to the Artifacts section
https://github.com/quicksilver/Quicksilver/actions/runs/1432475302
> Upload artifacts to PRs and merges

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
Makes sure text wraps in the right place. Fixes #2127
> Set text editor size correctly

- Quicksilver/Code-QuickStepCore/QSCatalogEntry.m
- Quicksilver/Code-QuickStepCore/QSPlugIn.m
- Quicksilver/Code-QuickStepCore/QSRegistry.m
I can probably push something this simple straight to master, right?
> Typo: ocurred -> occurred

- Quicksilver/Code-QuickStepCore/QSProcessSource.m
> fix Toggle Application for showing some apps

- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.m
> resize the interface on the main thread

- Quicksilver/Nibs/QSCatalog.xib
- Quicksilver/Nibs/QSPlugInsPrefPane.xib
- Quicksilver/Nibs/QSTriggersPrefPane.xib
Attempt to fix #2673
Creating PR to test the GH Action-built version.
> Increase default width of plugin pref pane sidebars

- Quicksilver/Quicksilver.entitlements
> Add more entitlements to Quicksilver

- .github/workflows/ci.yml
https://github.com/quicksilver/Quicksilver/issues/2727
> Create and upload checksum for dmg

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSActionProvider_EmbeddedProviders.m
Fixes #2035
Let's save this for 2.1.0
I removed code related to resolving aliases, as it seems NSWorkspace has got smarter, and no longer requires you to resolve aliases.
> When opening multiple files, open them 'together' like Finder

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.h
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepInterface/QSObjectCell.m
- Quicksilver/Code-QuickStepInterface/QSResultController.m
- Quicksilver/Code-QuickStepInterface/QSTableView.h
- Quicksilver/Code-QuickStepInterface/QSTableView.m
Several more optimisations to speed up searching/general usage of QS.
The NSZeroRect change along gives a decent speed boost (to icon drawing). The rest are pretty simple changes. Once this is merged, I'll probably do a third and final round of optimisations. Instruments.app is so handy :)
I think we're sufficiently ready to make a 2.1.0 release - I think this can go in there
> Further QS Speed Optimisations

- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSScreenshots.h
- Quicksilver/Code-QuickStepCore/QSScreenshots.m
- Quicksilver/PropertyLists/QSRegistration.plist
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
This is based on the "Latest Download" proxy object, which has an implementation that I've adapted and simplified.
> Add a "Latest Screenshot" proxy object. Implements #2749.

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSAppleScriptActions.m
Fixes https://github.com/quicksilver/Quicksilver/issues/2604
Please see discussion at the issue.
> Add support for JXA actions

- .github/workflows/ci.yml
- Quicksilver/Tools/qsrelease
- Allow users to specify the configuration
- Provide a debug version as a build artifact
>  Provide a debug build of Quicksilver as a build artifact

- Quicksilver/Code-App/QSController.h
- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-QuickStepCore/QSTaskController.m
- Quicksilver/Code-QuickStepInterface/QSInterfaceController.h
- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
Fixes #2874
Does what it says on the tin. No need for notifications anyway, KVB is much cleaner.
> Use KVB to watch for tasks that are processing

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.h
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
> Also clear text when clearing object view

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSAppleScriptActions.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Fixes https://github.com/quicksilver/Quicksilver/issues/2604
Would love any feedback from @pjrobertson or @skurfer (on anything but variable names, but I guess that's fine too 😆).
> Fix direct and indirect type handlers for JXA

- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSMnemonics.h
- Quicksilver/Code-QuickStepCore/QSMnemonics.m
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Core Support Tests/Core_Support_Tests.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSDirectoryParser.m
- Quicksilver/Quicksilver Tests/Quicksilver_Tests.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Preflight.xcscheme
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Quicksilver Distribution.xcscheme
- Quicksilver/Tests/Tests-QSCore/QSFileObjectTests.m
- Quicksilver/Tools/qsrelease
- Revert "Disable parellalize builds for preflight"
- Fix comment prefix
- Remove multiple deps from Quicksilver Tests to fix cycle in dependencies
See also: https://github.com/quicksilver/Quicksilver/issues/2583
> Fix cycle in dependencies to get tests running

- Quicksilver/Code-QuickStepCore/QSPaths.m
- Quicksilver/Quicksilver Tests/Quicksilver_Tests.m
- Quicksilver/Quicksilver.xcodeproj/Quicksilver Distribution.xctestplan
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Quicksilver Distribution.xcscheme
- Quicksilver/Quicksilver.xcodeproj/xcshareddata/xcschemes/Quicksilver.xcscheme
- Quicksilver/Tests/Tests-QSCore/QSPathsTests.m
- Quicksilver/Tests/Tests-QSCore/TestQSObject.m
- Quicksilver/Tools/qsrelease
- Quicksilver/Tools/qstest
Fixes https://github.com/quicksilver/Quicksilver/issues/2953
> Mock Application Support when running tests

- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSProcessMonitor.m
Hopefully fixes #2990, at least in part
> Try using the thread-safe dictionary

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSActionProvider_EmbeddedProviders.m
fixes https://github.com/quicksilver/Quicksilver/issues/3029
> check for nil path
