- Quicksilver/Code-QuickStepCore/QSObject_URLHandling.m
If you've been using the web search plugin, you'll have noticed that the icons are all like this:
http://grabicon.com/icon?domain=https://example.com&size=32
That's because the API has changed slightly and we now need to provide an 'origin' parameter. Apparently if we go over our 'api limit' we won't be able to load more icons, so I've got in touch with the guys
> Switch to new grabicon.com domain/API

- Quicksilver/Code-QuickStepCore/QSResourceManager.m
the underlying bug seems to be fixed in 10.10.2
> yank out the safeImageName work-around

- Quicksilver/PlugIns-Main/Finder/Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ca-ES.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/cs.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/de.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es-ES.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es-MX.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/et.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/fi.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/fr.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/id.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/it.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ja.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ko.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/nb-NO.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/nl.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/pl.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/pt-BR.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ru.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/sv.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/th.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/tr.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/zh-Hans.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/zh-Hant.lproj/QSCatalogPreset.name.strings
…thanks to a recent comment on #683.
Apple clearly can’t decide where they want to store these things.
Should we just get rid of the Toolbar Items preset? It doesn’t work either and I’m not sure if it’s even a thing you can do now.
> Sidebar items

- Quicksilver/Code-App/QSCatalogPrefPane.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepCore/QSCatalogEntry.h
- Quicksilver/Code-QuickStepCore/QSCatalogEntry.m
- Quicksilver/Code-QuickStepCore/QSCatalogEntry_Private.h
- Quicksilver/Code-QuickStepCore/QSHistoryController.m
- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSNotifications.h
- Quicksilver/Code-QuickStepCore/QSObjectSource.h
- Quicksilver/Code-QuickStepCore/QSObjectSource.m
- Quicksilver/Code-QuickStepCore/QSTask.m
- Quicksilver/Code-QuickStepCore/QSTriggerCenter.m
- Quicksilver/Nibs/QSUserDefinedProxySource.xib
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSCatalogEntrySource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSDefaultsObjectSource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSUserDefinedProxySource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSWebSource.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
This is a rebase of #1601.
-  [x] Fix the auto-reenabling presets after a restart
> Cleanup catalog entry API

- Quicksilver/Code-QuickStepCore/QSCatalogEntry.m
I ran across this the other day and `git bisect` led me to acf09391cc44367905d8792a93fea47305f22fb8
I had to look closely to find the problem, but those methods weren’t actually duplicates. One of the `for` loops starts at 0 and the other starts at 1. Maybe they could be consolidated into one that takes an argument, but for now, it works.
> restore the logic of catalogSetIndexPath

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
A small enhancement to address some of the concerns raised in the discussion on #925.
Basically, for any type in `QSTypeDefinitions`, in addition to the name and icon, you can also specify an integer for one of the existing spacebar behaviors.
This made the special-case code for URLs unnecessary, so I removed it. I’ve added the necessary entry for URLs to the plist in the core plug-in. If this is merged, I’ll also add something for search URLs to the web search plug-ins, and iTunes tracks in that plug-in.
I’ll document the new key and its possible values in the plug-in ref, too.
> allow type-specific smart spacebar behavior

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
Basically if anything is typed immediately before the slash (not just a slash), then it's OK to drill down (I think).
I also got rid of one `if()` for the case where `/` is long pressed. I didn't like the fact that it would immediately drill down into 'Macintosh HD' if you held `/` for long enough. I'm happy for this to be changed back though if there's a case for it
> Fix typing / quickly. Fixes #2077

- Quicksilver/Code-QuickStepCore/QSObject_StringHandling.m
> provide a nicer fallback behavior for stringValue

- Quicksilver/Code-App/QSController.m
rework of @clarkewd's pull request. #1935 
Adds in Rob's suggestion of moving the check for this to the 'whole' of the `checkForCrash` method
> Add preference to hide crash reporter on restart

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSPaths.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
I sense we don’t have a lot of time, so hopefully one of you can look at this soon. :smile:
fixes #2079
> recent documents for El Capitan

- Quicksilver/Code-App/QSSimpleWebWindowController.m
- Quicksilver/Code-External/CGSPrivate.h
- Quicksilver/Code-External/NDClasses/NDHotKeyEvent.m
- Quicksilver/Code-External/NDClasses/NSAppleEventDescriptor+NDCoercion.m
- Quicksilver/Code-External/NDClasses/NSURL+NDCarbonUtilities.m
- Quicksilver/Code-QuickStepCore/QSAlertManager.m
- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSObject_Menus.m
- Quicksilver/Code-QuickStepCore/QSPlugIn.m
- Quicksilver/Code-QuickStepEffects/QSWindow.m
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
- Quicksilver/Code-QuickStepFoundation/QSThreadSafeMutableDictionary.m
- Quicksilver/Code-QuickStepInterface/QSObjectView.m
- Quicksilver/Code-QuickStepInterface/QSTextViewer.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Here's an attempt at bringing down the count of warnings. I even *tried* to kill the ND classes ;-).
> Deprecation cleanup

- Quicksilver/Code-QuickStepFoundation/NSMetadataQuery+Synchronous.m
> Handle the $ variables in Spotlight queries

- Quicksilver/Code-App/QSController.h
- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSSimpleWebWindowController.m
- Quicksilver/Code-External/CGSPrivate.h
- Quicksilver/Code-External/NDClasses/NDHotKeyEvent.m
- Quicksilver/Code-External/NDClasses/NSAppleEventDescriptor+NDCoercion.m
- Quicksilver/Code-External/NDClasses/NSURL+NDCarbonUtilities.m
- Quicksilver/Code-QuickStepCore/QSAlertManager.m
- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSObject_Menus.m
- Quicksilver/Code-QuickStepCore/QSPlugIn.m
- Quicksilver/Code-QuickStepEffects/QSWindow.m
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
- Quicksilver/Code-QuickStepFoundation/QSThreadSafeMutableDictionary.m
- Quicksilver/Code-QuickStepInterface/QSObjectView.m
- Quicksilver/Code-QuickStepInterface/QSTextViewer.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Because catching signals and exceptions only in debug mode felt weird. I had never before seen that "stability" alert before yesterday ;-).
> Kill error handling

- Quicksilver/Code-External/CGSPrivate.h
- Quicksilver/Code-QuickStepEffects/QSWindowAnimation.m
I've did it again. In my eagerness to silence warnings, I broke CGSPrivate.
I was trying to fix the Cube issues (since @skurfer was kinda expecting that from #2144) and noticed a hard crash (the same as #1811). So this one stops the crash, but the animation is still horrible (here I can see it jump down (topscreen/topwindow distance seem to become bottomscreen/bottomwindow) and turn to some invisible window side before getting a hold of itself...
I'll try to pinpoint what's going wrong with it, but I have no clue whatsoever about what. is. going. on.
I'll merge that ASAP because it's a quick fix. Just wanted a heads up to you guys.
> Fix CGSPrivate (again)

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
After much twiddling with debuggers and Flashlights, I think I got it.
The problem is that sometimes, the calculation of the containing scrollview doesn't end on an integral rect. [This](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m#L746), returns this rect `
(origin = (x = 1.25, y = 1.25), size = (width = 57.5, height = 17.5))` which is then set as the scroll view frame, and this triggers a bug within the layout code where the text fields tries to adapt to that weird size but just ends up blowing up the stack because it's not pixel-aligned.
We might want check the various affected interfaces so this does not look too jarring visually.
> Fix for #2111

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepFoundation/NSURL_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSURL_BLTRExtensions.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSDirectoryParser.m
Sorry for the name, *you* know that's a hard problem ;-).
This resurrects the switch to NSURL bookmarks I tried to do (#2075), since I wanted to fix the class of network-alias-stalls bugs we have and the main QS method we had actually doesn't handle all the bells and whistles of bookmark resolution. Maybe I should have added a comment on `-[NSFileManager resolveAliasAtPath:]` and friends but, well, I didn't. Consider yourselves warned :smirk:.
This one fixes the issue Rob had with the hundreds of warning messages had because *symlinks*. Since I wasn't keen on basing the new resolver because of [shaky grounds](http://digitalleaves.com/blog/2013/09/nsurl-files-equality-comparison-and-equivalency/), I preferred to keep the symlink-checking separate.
There's also a fix for `-infoRec` …
> Modern aliases

- Quicksilver/Code-App/QSController.m
Turns out we made 1.3.0 10.9+ only, but forgot to change the warning in QSController
> Warn users when trying to run the app on 10.8

- Quicksilver/Code-QuickStepFoundation/NSMetadataQuery+Synchronous.m
> Return nothing if there is nothing to search for

- Quicksilver/Tools/travis/check_indent.rb
Don't worry about indents inside comment blocks
I saw that the test on @skurfer's  `objectchosen` branch were failing because of bad spaces/tabs in comment blocks. This change allows spaces/tabs/anything in comment blocks, although I'm still not sure if we should do this. If we're enforcing one format over the other, then shouldn't we also do that inside comment blocks?
Discuss ;-)
> Fix check_indent false positives on comment blocks

- Quicksilver/Code-QuickStepFoundation/NSFileManager_BLTRExtensions.m
I think this is going to be controversial. This makes QS never try to mount network volumes when resolving aliases, as right now we have no way to discern whether this is a "user-initiated" resolution, or some background scan.
Thinking about it, I should have split that... The second part makes the resolution fail completely instead of returning itself. Say you're browsing some folder containing one of those remote aliases, if you right-arrowed (and had the patience to wait for it to fail), you'd end up with a new result set with only that alias, instead of the expected bump.
> Don't mount volumes when resolving aliases

- Quicksilver/Code-QuickStepCore/QSPreferenceKeys.h
- Quicksilver/Code-QuickStepInterface/QSObjectCell.m
- Quicksilver/Nibs/QSAppearancePrefPane.xib
- Quicksilver/Resources/QSDefaults.plist
Adds 4 new preferences for controlling the appearance of text in a `QSObjectCell`:
* Underline matched text
* Make matched text “glow” (a shadow that matches the details color, which is the text color faded by 20%)
* Allow users to turn off “name ⟷ label” and just show the matched string (the original behavior). A gift for @hmelman and I’m sure others.
* Allow users to disable text tightening. It causes letters to overlap with some fonts.
This is mostly motivated by some problems that were plaguing users, and my long-time hatred of the underlined letters. (I’ve been using “glow” for like a year locally.) I thought it made sense to do them all together. We could also add a color picker for matched text and some other options, but this is a good starting point.
Note that I updated the NIB’s …
> Text preferences

- Quicksilver/Code-App/QSController.m
Not sure why this would have been prevented. The line above already protects against a circular reference.
I see that I’m the one that wrote it, but I was just rewriting a test that was already there.
> allow Quicksilver Selection to refer to other proxy objects

- Quicksilver/Code-App/QSController.h
- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-QuickStepCore/QSCommand.m
- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObject_StringHandling.m
- Quicksilver/Code-QuickStepInterface/DefaultBindings.qskeys
- Quicksilver/Code-QuickStepInterface/QSCollectingSearchObjectView.h
- Quicksilver/Code-QuickStepInterface/QSCollectingSearchObjectView.m
- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.h
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSObjectActions.m
- Quicksilver/PropertyLists/QSRegistration.plist
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Tests/Tests-QSCore/TestQSObject.m
That is, when a user does something to explicitly say “this is the thing I was searching for”, add it to the history and save the mnemonic used. (I’m thinking there’s never a reason to do one without the other in the first pane, so they’re married now. :wedding:)
I’ve added the two methods to some additional areas that indicate user acknowledgment of a match, like `shortCircuit`, `moveRight`, and Quick Look. I added them to `insertTab` too, but changed my mind. If you *did* find the thing you want and are tabbing to select a different action, you’re probably about to execute the command, which will take care of things.
I’d consider a hidden pref that makes the history act more like it did before, where just typing random characters adds things to history whether or not you find the result …
> only store “chosen” objects in history

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
I’m not sure of all the consequences, since the two implementations of `setObjectValue:` are pretty different. But since all we’re doing is wiping things out, the version in `self` seems to make more sense.
> call the local setObjectValue when clearing

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSObjectActions.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSAction.description.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSAction.name.strings
A new action that does the same thing as `⌃⌘]`, as suggested in comments on #2092.
Maybe “explode” is the wrong word for the user-facing name. I’m open to suggestions.
> Explode Combined Objects

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.h
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
As promised, a pull to reduce the use of mutable objects. First for `splitObjects`, then for various arrays stored for the search object view. Only the `resultArray` really needs to be mutable as that's what is changed as you search
> Reduce Mutables

- Quicksilver/PlugIns-Main/Finder/Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSSharedFileListSource.h
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSSharedFileListSource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Updates the following catalog presets to work in …whatever version of OS X broke them.
* Finder Sidebar Items
* Recent Applications
* Recent Documents
* Recent Servers
* Favorite Servers
This surely breaks those things for older OS X versions, but this crap changes so often, I wonder if they were even working in the first place. :smiley:
fixes #2187
> Fixes for Recents and Favorites

- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
Used the “informally” deprecated method we were already using. I suppose we should update those one day.
> Update history and mnemonics when dragging

- Quicksilver/Code-QuickStepInterface/QSResultController.m
I recently noticed some exceptions in my system log originating from QS. I've put a few examples in a gist: https://gist.github.com/mattbeshara/b07bef9bca8662d4e8e2d3c6ce306bb7
The cause seems to be that sometimes when I have the search window open, QS isn't getting the type of NSEvent it expects from [NSApp currentEvent]. A couple of "SysDefined" events sometimes occur where the code only expects either NSKeyDown or NSKeyUp events. I don't know what those unexpected events are, what triggers them, or when they occur, so I don't know how to reproduce this for those specific events. The code checks that the function key is held down before calling [NSEvent isARepeat], but I don't know what relationship that may have with the non-key events it's getting.
Getting the exception thrown is …
> Prevent an exception from being thrown

- Quicksilver/Code-QuickStepCore/QSPlugInManager.m
When you do an app upgrade, Quicksilver first downloads the app, then checks for plugin updates and installs them. When installing these plugins a notification pops up saying the plugin is installed as per [this line](https://github.com/quicksilver/Quicksilver/blob/master/Quicksilver/Code-QuickStepCore/QSPlugInManager.m#L865)
The message 'Relaunch Required' really shouldn't display if Quicksilver is in the middle of an upgrade process (for which a relaunch would be required anyway)
> Don't mention 'relaunch required' when updating plugins as part of an app upgrade

- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.m
Fixes #2234  - see that for a full discussion.
The 2nd commit also fixes a usability bug I came across testing this:
* 1st pane: type text
* 2nd pane: choose 'Create File [...]'
* Tab to 3rd pane to open it up
* Select an object in the 3rd pane
* Tab back to the 1st pane
Notice how the 3rd pane closes, hiding your selected object. The truth is, even though the 3rd pane is hidden its value will still be used when executing the action, so it should really stay open to make it more explicit to the user "this object will be used". If they don't want a 3rd pane action anymore they can just wipe it out with ⌃U as per usual
> Be more specific about when the 3rd pane should open/close

- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSAppleScriptActions.m
Fixes the stuff in #2071 
Thanks @Sesquipedalian for reporting this and and also Mike Petonic for alerting me to this on the dev forums. Quite a big usability problem.
There is now an addition of a '3rd pane not-optional' choice for 3-pane actions.
That is, if you set the 'get argument count' part to return `-3` then the 3rd pane is optional. If it returns `3` then the 3rd pane is *not* optional (and will display by default).
I used -3 and 3 as I thought it was kind of intuitive `-3` meaning optional, `3` meaning not optional.
Open to other suggestions though
> Applescript third pane

- Quicksilver/Code-App/QSAboutWindowController.m
- Quicksilver/Code-App/QSPlugInsPrefPane.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepCore/QSCrashReporterWindowController.m
- Quicksilver/Code-QuickStepCore/QSPluginUpdaterWindowController.m
- Quicksilver/Tests/Tests-QSCore/TestQSObject.m
This gets it passing. It’s more like real-world usage now too, so that’s good.
> Equality test

- Quicksilver/Code-QuickStepCore/QSCatalogEntry.m
It turns out the validity check was already happening on the correct queue, but it could get stuck waiting for that queue, as shown in #2016.
> don't check index validity during a scan

- Quicksilver/Code-QuickStepInterface/QSTableView.h
I found those while looking at the Clipboard module — which looks like the only place it's used, along with Shelf (which already has it commented out).
> Deprecate some delegate methods that have Cocoa replacements

- Quicksilver/Code-App/QSCatalogPrefPane.m
- Quicksilver/Code-QuickStepCore/QSCore.h
- Quicksilver/Code-QuickStepCore/QSExecutor.m
- Quicksilver/Code-QuickStepCore/QSObject.h
- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObjectHandler.h
- Quicksilver/Code-QuickStepCore/QSObjectSource.h
- Quicksilver/Code-QuickStepCore/QSObjectSource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSUserDefinedProxySource.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
A rejig of #2246, with some tweaks to check_indent because it didn't like documentation comments and staged changes.
> Catalog protocols

- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepCore/QSObject_StringHandling.m
- Quicksilver/Code-QuickStepCore/QSPaths.h
- Quicksilver/Code-QuickStepCore/QSPaths.m
- Quicksilver/Code-QuickStepCore/QSTrigger.m
- Quicksilver/Tests/Tests-QSCore/TestQSObject.m
I could never induce `splitObjects` to call `children`, even following the steps in #2242, but the potential for an infinite loop was undeniable. Good catch, @pjrobertson!
This should prevent such a loop. The second commit may or may not help as well, but at worst, it makes things more efficient.
> avoid hang in stringValue

- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
Fixes #2268 while keeping the "clear on close" behavior of aeaa261352e3caa42838e3a1f4caa2a9ef90953c
> Only hide the interface after everything has been set up for execution

- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.h
There will surely be other changes necessary, but this is the only thing completely preventing QS from building under Xcode 8.
> declare build version in the interface

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
This should have always been there, right? Why wasn’t it?
I know retain cycles are something to worry about, but I’m sure the affected objects have a dozen references to them in various places anyway.
The first commit is the main thing, but I fixed some other minor things while investigating. My gut tells me all that left-arrow code needs to be refactored, but I’m not going any deeper for the moment.
> assign parents

- Quicksilver/Code-QuickStepCore/QSObject.h
- Quicksilver/Code-QuickStepCore/QSObject.m
R[TFM][1] FTW!
This should fix the problems we’ve seen with duplicates in the third pane (#2097) and God knows how many other places.
This is also, I’m sure, the _true_ fix for #1459. I remember you were trying to clean up the way identifiers were managed at the time @pjrobertson and we had to revert the changes, but could never figure out why. We can probably re-implement those changes now (once I figure out what they were).
[1]: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSSet_Class/index.html#//apple_ref/occ/instm/NSSet/member:
> prevent duplicate QSObjects

- Quicksilver/Code-QuickStepCore/QSCommand.m
- Quicksilver/Code-QuickStepCore/QSNotifications.h
- Quicksilver/Code-QuickStepCore/QSProxyObject.m
- Quicksilver/Code-QuickStepInterface/QSObjectCell.m
- Quicksilver/Code-QuickStepInterface/QSResultController.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
Fixes #2069, which was the original motivation, but I also put this out there to get your opinion on the changes to the observers. I’ve long wondered what would happen if we did this.
(My motivation for trying was to get the mini-icons in a comma trick collection to update. It was either this, or another complicated mess of adding and removing observers for individual objects.)
I think it’s OK because we can tell the OS a billion times that a view needs to be redrawn, but it won’t actually redraw unless it decides it’s a good time to do so. Is that correct? In any case, icon changes don’t come in too rapidly. The only “problem” I see is that all three panes get the notice and ask to be redrawn.
Before this is merged, I’d also like to see if we can get other places to observe icon changes. …
> show proxy object icons more reliably

- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepCore/QSAlertManager.h
- Quicksilver/Code-QuickStepCore/QSAlertManager.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSActionProvider_EmbeddedProviders.m
So, this is an alternate version of #2104. Sorry @skurfer, I didn't like the "one delegate to rule them all approach", though as I said earlier, it's because of the API.
This one uses a block to notify what choice the user made. Right now it uses the same kind of block than the alerts do, but depending on some discussion, that can change. I prefer that to moving gobs of important code to [unrelated places](https://github.com/quicksilver/Quicksilver/pull/2104/files?diff=unified#diff-29f2dfd46753000b6ca6b67b790754d9R481). I do agree the update code is not the most streamlined code to pick on, but, well...
Something I planned for but didn't yet handle is automatically escalating notifications to alerts via the delegate callback (that's why I started on cleaning up `QSAlertManager` first, …
> Notification rewrite

- Quicksilver/Code-QuickStepInterface/QSObjectView.h
- Quicksilver/Code-QuickStepInterface/QSObjectView.m
I thought I had found all the places. Here’s one more.
That `redisplay` method keeps creeping outward, when we really only need it on the one class. If anyone has an idea on a cleaner way to handle this, let me know.
> improve appearance for multiple dropped files

- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
The problem is that clearing the search string too early means mnemonics are not saved, so if we move the mnemonic saving code earlier this fixes it.
The reason we want to clear the search string on interface close is a UI thing. See this comment: https://github.com/quicksilver/Quicksilver/pull/2249#issuecomment-236476810
Fixes #2302
Fixes #2300
Related to #2268 #2269 
------
OK guys take a look at this. Basically, I took a look at what @tiennou had done in 2b2cc2dfe4b7a3d4270581527d9ddd130bd8ce6f but realised that that `if (!cont) {}` code is needed but understood why Etienne was doing this - because closing the interface meant the search string was cleared, which meant mnemonics could not be saved (since that was done later on).
Instead, what I did was to make saving the mnemonics …
> Another go at ensuring search string is cleared when closing interface

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepFoundation/QSUTI.m
This seems to fix #2299. At the very least, it’s slightly more efficient.
> avoid calling QSUTIForAnyTypeString() twice

- Quicksilver/Code-QuickStepInterface/QSCollectingSearchObjectView.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
Right now, “Reset search after” is crippling the training/learning process. (And it’s enabled by default, so this probably affects a lot of people.) Possible solutions:
1. Keep the matched string until the interface is dismissed or the selection is explicitly cleared
2. Rip out the “Reset search after” feature entirely
3. Add a yet another string (a 4th?) to keep track of the abbreviation until the interface is dismissed
I’ve attempted 1. Thoughts?
The first commit fixes a bug I ran across while working on this. (You couldn’t clear the selection when using the comma trick unless the current object was in the collection.) Seemed like the best solution.
Fixes #2301
> String dance

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObject_PropertyList.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Tests/Tests-QSCore/TestQSObject.m
An attempt to alleviate some of the delays we’ve seen related to UTI look-ups.
I also tried to more generally speed up comparisons between QSObjects since they seem to be far more common than I thought.
(One example: When an `NSSet` is copied, the objects aren’t just blindly thrown into a new set. As they get added, the new set checks *again* to make sure there are no duplicates, which triggers calls to `isEqual:` for everything in the set. This happens twice in `purgeImagesAndChildrenOlderThan` alone.)
I look forward to hearing how terrible some of these changes are and why. 😝 I was just going for raw speed, OK?
> speed up QSObject comparisons

- Quicksilver/PlugIns-Main/Bezel/QSBezelInterface.xib
- Quicksilver/PlugIns-Main/PrimerInterface/Primer.xib
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ca-ES.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/cs.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/de.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en-GB.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es-ES.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es-MX.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/es.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/et.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/fi.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/fr.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/id.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/it.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ja.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ko.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/nb-NO.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/nl.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/pl.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/pt-BR.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/ru.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/sv.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/th.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/tr.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/zh-Hans.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/zh-Hant.lproj/QSCatalogPreset.name.strings
- Quicksilver/PlugIns-Main/QSHotKeyPlugIn/QSHotKeyTrigger.xib
- Quicksilver/QSDroplet/QSDroplet.xib
- Quicksilver/Resources/DefaultMnemonics.plist
I noticed a warning about the droplet NIB. It got overlooked when I updated the deployment target. That’s all that’s changed.
And Internet Explorer… Probably safe to drop that, right?
> clean up some old stuff

- Quicksilver/Code-QuickStepCore/QSDefines.h
- Quicksilver/Code-QuickStepCore/QSNotifications.h
- Quicksilver/Code-QuickStepCore/QSProxyObject.h
- Quicksilver/Code-QuickStepCore/QSProxyObject.m
- Quicksilver/Code-QuickStepCore/QSTriggerCenter.m
- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
I think I’ve finally figured out how to get rid of the timer.
There are generally two places we want to resolve a proxy object: to show it in the interface, and to use it in a command. Once resolved, we want to hold onto that value until one of two things happens: The command is finished using the object, or the interface was dismissed.
Common scenarios (and their effect on the proxy):
Select and do nothing.
1. Select a proxy in the interface (resolve)
2. Dismiss the interface without doing anything (release)
Run a trigger.
1. Run a command that uses a proxy object (resolve)
2. The trigger’s command finishes (release)
Those are fine on their own, but an even more common scenario combines them in a weird order.
1. Select a proxy in the interface (resolve)
2. Hit Return to run the command, …
> better proxy caching

- Quicksilver/Code-QuickStepCore/QSLibrarian.m
Of course `git blame` said “look in the mirror” on this one.
> don’t add identifiers to string objects

- Quicksilver/Code-QuickStepCore/QSVoyeur.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
I pushed an updated version of VDKQueue to our fork (there was some movement in the Github Network).
Note that I don't think VDKQueue is responsible for our deadlocks 😉.
> Don't trigger VDKQueue on the main thread

- Quicksilver/Code-App/QSTaskViewController.m
- Quicksilver/Code-QuickStepInterface/QSInterfaceController.m
This should fix the CA transaction warnings we have (at least the ones I saw).
I went pretty heavy-handed on the proxy thing, but I didn't want to make all `QSTask`'s accessors to become main-thready-asyncy...
I'll check that I didn't forget some of the keypaths though (I haven't checked everything, and I don't think we have an easy indeterminate progress one anywhere).
It seems to also fix the flicker we had, so 👍.
> Fix CA transactions warnings

- Quicksilver/Code-QuickStepCore/QSCore.h
- Quicksilver/Code-QuickStepCore/QSStringRanker.m
- Quicksilver/Code-QuickStepFoundation/NSString_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSString_BLTRExtensions.m
- Quicksilver/Code-QuickStepFoundation/QSFoundation.h
- Quicksilver/Code-QuickStepFoundation/QSSense.h
- Quicksilver/Code-QuickStepFoundation/QSSense.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Tests/Tests-QSFoundation/TestQSSense.m
This is also a really old branch (2012 was a good year !).
So, we have 2 different versions of the ranking algorithm in-tree, both dating back from the Dawn of Time. The main ranking loop would use QSSense (through `QSStringRanker`). I haven't seen any use of the `NSString` category, but since it's hidden behind forwarding, it might be used sometimes.
~~They *had* a differing behavior (but I never found the time to thoroughly check).~~
The differing behavior was introduced in 87d328a actually. The comparison options are also a give-away (QSSense is case and diacritic insensitive and respect localization, the other is just case-insensitive.
So THE DIFFERENCE is what it is.
I've added a test case for it, because I wanted to 1) see it work 2) see what was different.
> QSSense fixup

- Quicksilver/Tools/qsrelease
I’ve had it commented out in the build script for months. Time to make it official.
> remove xctool

- .travis.yml
- Quicksilver/Code-QuickStepInterface/QSHotKeyEditor.m
I removed the problematic entries, and switched the others to use the newer names. It means we can’t build with Xcode 7 any more, but that ship already sailed with `NSWindowStyleMask`. I’ll add another commit to update Travis.
Take a quick look at this if you can @tiennou.
> Event changes for hotkey editor

- .gitmodules
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Because I got *really* tired of `objc[14949]: Class FMDatabase is implemented in both $1 and $2. One of the two will be used. Which one is undefined.` * @[Safari, Firefox, Chrome] * @[FMDatabase, FMResultSet, FMStatement] on each launch.
Note, I'm pretty sure it works, but just in case, you *should* try running QS, right-click "Show in Finder" the Products/fmdb.framework and delete that from the built product **as soon as QSFoundation is built**, before it launches (else Xcode will rebuild it). You'll either get a successful launch, or a `dyld` failure.
> Add FMDB as an external dependency

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSObject_Pasteboard.m
- Quicksilver/Code-QuickStepCore/QSPlugInManager.m
- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.m
I'm currently working through the crashers for 4020.
For now, there's only one (I'm still massaging my crashreport wrangling machinery 😉).
- 324 reports currently, with 171 "different" crash locations.
- top crash (which is the only fix for now) has 100 occurrences
- second is `*** Collection <__NSDictionaryM: 0x608000047770> was mutated while being enumerated.` with 32.
Note that it's likely I'll continue bashing on this.
> An assortment of 4020 bugfixes

- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSMainPreferencePanes.m
- Quicksilver/Code-App/QSUpdateController.h
- Quicksilver/Code-App/QSUpdateController.m
- Quicksilver/Resources/DefaultsMap.plist
Since I'm currently accessing the 'ternet from my world-changing iPhone, I just noticed that the update system does its thing on the main thread. When there's a DNS hiccup at the same time, you end up with a spinning-beachball QS for _too long_.
This fixes it by generous use of dispatch queues. This also makes its API more self-contained.
Not completely tested, by which I mean I clicked on the "Check Now" button, but that's all I did.
As a bonus, every user-facing string is now wrapped in a gentle `NSLocalizedString`.
> Bash QSUpdateController out of the main thread.

- Quicksilver/Code-App/QSController.h
- Quicksilver/Code-App/QSController.m
- Quicksilver/Nibs/MainMenu.xib
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/PropertyLists/QSRegistration.plist
As promised.
* enabled by default
* scoped to be active only in Quicksilver
* uses ⌃⌥⌘Q by default
Since it’s a trigger, users on 10.12 or older can change it back or change it to something else if they want.
> redefine Relaunch as a trigger

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSPaths.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSSharedFileListSource.m
…and various recent/favorite catalog presets.
Doing a string replacement on the extension feels ugly, but I don’t think we have a way to restrict presets by OS version, and that’s where the path is defined.
As discussed in #2396
> Support for recent documents in High Sierra

- Quicksilver/Code-QuickStepFoundation/QSSense.h
- Quicksilver/Code-QuickStepFoundation/QSSense.m
I'm back! Although for my own selfish needs :'(
Most non-latin languages have formal romanizations from the native script to latin (e.g. 中国 -> zhongguo). This change allows you to search using latin characters for non-latin names/labels. It should apply to all latin languages that have formal romanizations.
One issue that I had with this is that when you romanize a non-latin search string (e.g. 中国) its length is changed (often increased):
```
中国 => length 2
zhongguo => length 8
```
This would cause problems when displaying the characters that matched in the string (normally done by underlining them in the SOV. To solve this problem I just opted to not show which letters matched:
Note that this change will have an affect on all users, and my suspicion is most of our users are limited to …
> Transliterate non-latin strings into latin if there's no match

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.h
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSRegistry.h
- Quicksilver/Code-QuickStepInterface/QSResultController.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/Nibs/QSWebSource.xib
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSWebSource.h
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSWebSource.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSObjectSource.name.strings
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Resources/ResourceLocations.plist
As discussed way back in #767, this adds some UI that will let you scan file contents from a remote URL.
One thing I can’t figure out is how to get the URL to “stick” when the text box loses focus. (I hate dealing with NIBs.) But other than that, it works.
There are some small bonus fixes at the end.
> URL Object Source

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSObjectActions.m
- Quicksilver/PlugIns-Main/QSCorePlugIn/QSCorePlugIn-Info.plist
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSAction.description.strings
- Quicksilver/PlugIns-Main/QSCorePlugIn/Resources/en.lproj/QSAction.name.strings
Disabled by default.
Should have done this years ago. Yes, there’s an item like this in the menu for debug builds, but what kind of animal has the Dock icon enabled? And what if you need to see something currently in memory and aren’t running a debug build? What if you need info from a user on another system?
> add an action for dumping object details

- Quicksilver/Code-QuickStepCore/QSLibrarian.m
I nearly did this before, but decided not to based on the fear that if you were to type (or paste) an existing object’s identifier in text mode, the string object representing the identifier would replace the real object in the catalog. That doesn’t seem to be the case.
You do get some weirdness with history (you can’t store both an object and a string with its identifier), but that’s an edge case I don’t think we need to worry about.
> use string value as identifier for string objects

- Quicksilver/Code-QuickStepCore/QSCommand.m
Fixes issue #2419
This *should* fix #2419 (I think), it seems that in this case:
1. You create a trigger for an dObject that's not in the catalog
2. That dObject subsequently gets added to the catalog
3. You resave the trigger (I guess it happens on every quit of the app)
Then the trigger would have both a directArchive (created originally when the object isn't in the catalog) and then subsequently a directID (when the object gets added to the catalog). This causes problems in `QSCommand.m:-(QSObject *)dObject` (I think).
Now the ideal solution would be to store *both* the directID and directArchive, and (for the event that you add a trigger for something that's in the catalog, then it subsequently gets removed from the catalog) but that's another task for another day.
> Don't store IDs and archives for a QSCommand (in the plist)

- Quicksilver/Code-QuickStepCore/QSAction.h
- Quicksilver/Code-QuickStepCore/QSAction.m
- Quicksilver/Code-QuickStepCore/QSDefines.h
Allow more things to be defined for actions. Basically because I needed some of this for the new Audio plug-in.
I could have just created 12 actions by hand in less time than it took to figure out the block stuff, but I think it’s worth it. For an actual use-case, see https://github.com/quicksilver/Audio-qsplugin/blob/master/Audio/AudioAction.m#L31
Another place it can be used is Remote Hosts where many of the actions are just opening a URL with a different scheme.
> Action config

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
Children will only be loaded with right-arrow if `objectHasChildren:` returns `YES`. This was working for any application that still had `.sfl` files laying around, but it should have been checking for `.sfl2` files on 10.13+.
> fix test for recent documents under 10.13

- Quicksilver/Code-QuickStepCore/QSProxyObject.h
- Quicksilver/Code-QuickStepCore/QSProxyObject.m
I was trying to show nicer details for a proxy object by pulling them from the resolved object, but calling `resolvedObject` while getting details tends to happen before the object gets selected in the main interface. (I think because it appears in the results during a partial match.) That forces the object to be resolved and cached before it’s actually displayed.
There also seems to be something calling for details just after the interface is dismissed, which is even worse because of this sequence:
1. The user dismisses the interface
2. The proxy cache is intentionally cleared
3. Something calls `detailsOfObject:` which calls `resolvedObject` which grabs and immediately re-caches the current value of the proxy
Then, sometime later:
4. The user calls up the proxy
5. It has a (potentially …
> Background proxy side-effects

- Quicksilver/Code-QuickStepFoundation/NSWorkspace_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSWorkspace_BLTRExtensions.m
Deprecate and move away from the old NSWorkspace style app dicts.
This should fix #2482 as well as just generally clean up the code
We can't move away from the old style completely, because some plugins still use it. But it's nice to at least make a start... baby steps :P
Also: ideally we'd switch QSObjects that represent running processes (stored in the `QSProcessType` data key) to also use NSRunningApplication instead of these NSDicts, but again... baby steps. Assuming this code has no big problems, that would be the next step
> Use NSRunningApplication for app management

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSObject_Pasteboard.m
Just some small cleanups/fixes related to clipboard stuff.
Should reduce the amount of crap in the logs about `'bad data for XXXXX'` as well as `unexpected object for file path: (null)....`
> Clipboard cleanups

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSSharedFileListSource.m
I updated the path that gets scanned under High Sierra+, but I forgot to update the code that checks to see whether or not a rescan is necessary.
fixes #2514
> fix recent applications/documents

- Quicksilver/Code-QuickStepInterface/QSLargeTypeDisplay.m
- Quicksilver/Code-QuickStepInterface/QSTextViewer.m
This prevents the app from crashing when dismissing the Large Type interface. I have a VM running Catalina, so I was able to test there too.
> don’t release Large Type windows on close

- Quicksilver/PropertyLists/Quicksilver-Info.plist
Some packaging tools were getting tripped up on the representation of the Escape key. This appears to work just as well.
See #2527
> use the octal representation of the escape character

- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
Big Sure uses a major version 11 but minor 0.
Tests expected >= 10 **and** minor > 0.
> Fixed OS version tests for Big Sur.

- Quicksilver/Code-QuickStepFoundation/NSApplication_BLTRExtensions.m
Without this, running as Apple architecture -> `Relaunch Quicksilver` -> running as Intel.
This is the first line of Objective C I've ever written, but seems to work.
Related issue: https://github.com/quicksilver/Quicksilver/issues/2543
> Relaunch as ARM64 if running ARM64

- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Gets rid of a dozen or so build warnings.
> Apply Xcode-recommended localization updates

- .gitmodules
GitHub is removing the unencrypted Git protocol, see https://github.blog/2021-09-01-improving-git-protocol-security-github/.
> Replace git:// URLs with https

- Quicksilver/Code-App/QSTriggersPrefPane.m
- Quicksilver/Nibs/QSTriggersPrefPane.xib
Very simple. Sort the 'Trigger' (key shortcut) column using localizedStandardCompare so you get the sorting as per #2561 
Set it up in the Triggers pref pane xib as follows:
I had to remove [this line](https://github.com/quicksilver/Quicksilver/pull/2598/files#diff-609e1df55bef2b65d4983417a045d9711f7065d68b40d035fe4e2c3f9d6d114aL198) and bind the sort descriptors to NSUserDefaults in the xib as well - manually binding causes issues with the NSUserdefaults value of just `compare:` over-writing the `localizedStandardCompare:` value.
> Order triggers using localizedStandardCompare

- Quicksilver/Code-App/QSUpdateController.m
- Quicksilver/Code-QuickStepCore/QSTaskController.m
- Quicksilver/PlugIns-Main/PrimerInterface/QSPrimerInterfaceController.m
Fixes warnings from Xcode of calling UI APIs on a background thread. Fixes #2579
Simple, just make sure that notifications about tasks are sent from the main thread, that way any view-stuff will also only be done from the main thread.
> Send task notifs from the main thread only

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSRegistry.h
- Quicksilver/Code-QuickStepCore/QSRegistry.m
Another very simple one. Add new actions to the existing dict, instead of replacing the dict entirely.
Right now, the last plugin to load QSApplicationActions for a certain app's bundle ID would chomp and overwrite any existing dictionary that was already loaded.
This change makes a Mutable dict for QSApplicationActions, and adds any new actions to the existing list, instead of blindly over-writing
Fixes #460
> Fix for #460

- Quicksilver/Tools/bltrversion
[See](See) also: https://github.com/Python-Markdown/markdown/issues/884
Python can't find the extensions when vendored like this; this change
seems to resolve the issue.
Additionally, it looks like the `extra` package may be deprecated.
> Fix PYTHONPATH issues with markdown instructions

- Quicksilver/Code-QuickStepInterface/QSBackgroundView.m
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/Nibs/ResultWindow.xib
In the same light as removing QSGlossyBar, this removes QSBackground view, and its custom 'fancy' drawing.
**Edit:** removing the view was a bit premature, it is actually used by a couple of plugins. Instead, I just removed the code draws the gradient backgrounds.
It makes the Results Window more 'flat' and hopefully more 'modern':
I also properly bound the results view header/footer text colour to the appearance prefs, fixing #1235
I'm a little bit more confident that these changes may help with the Catalina/Big Sur colour problems. Less archaic code is good, right?! :D
> Remove QSBackgroundView

- Quicksilver/Code-App/QSCatalogPrefPane.m
- Quicksilver/Code-App/QSPlugInsPrefPane.m
- Quicksilver/Code-App/QSPreferencesController.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-App/QSTriggersPrefPane.m
- Quicksilver/Code-QuickStepInterface/QSFancyTableView.m
- Quicksilver/Nibs/QSActionsPrefPane.xib
- Quicksilver/Nibs/QSCatalog.xib
- Quicksilver/Nibs/QSHelpersPrefPane.xib
- Quicksilver/Nibs/QSPlugInsPrefPane.xib
- Quicksilver/Nibs/QSPreferences.xib
- Quicksilver/Nibs/QSSetupAssistant.xib
- Quicksilver/Nibs/QSTriggersPrefPane.xib
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Resources/Guide.html
Removes previous 'custom' colours (yellow/purple etc.) from Triggers/Catalog/Plugins views, but by not hard-coding colours, we can use the system's defaults
Fixes #2638
> Fix colours for dark mode

- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.h
- Quicksilver/PlugIns-Main/QSCorePlugIn/Code/QSFileSystemObjectSource.m
Previously, if you have a Catalog entry with depth of 3, the file/folder watching would only work on the 'top' folder level and lower level folders wouldn't be watched. This change makes QS watch folders down to the 'depth' specified in the catalog entry's settings. Fixes #2509
https://user-images.githubusercontent.com/150431/154812514-19b8347a-aa11-4cca-866c-98587d2b1894.mov
Caveat: if you're to create a new sub-folder while QS is running, it won't add that to the watch list. QS will either need to be re-started, or the catalog entry toggled on/off. But I think that's a fairly small edge case.
> Watch all directories down to the 'depth' level

- Quicksilver/Quicksilver.entitlements
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
Allows loading un-signed plugins
Test pull request to have GH Actions build a signed copy to debug.
Related to https://github.com/quicksilver/Quicksilver/issues/2634#issuecomment-1059642928
> Disable library validation

- .github/workflows/ci.yml
- Quicksilver/Quicksilver.entitlements
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Tools/qsrelease
- Quicksilver/Tools/qssign
Turns out I was a bit premature in my last release. I set up the XCode proj to disable library validation, but of course we're signing using `codesign`. 
These changes should fix that.
> Library validation

- Quicksilver/SharedSupport/CHANGELOG
Big Sur was the visual overhaul, and Monterey that one followed it — I presume this was meant to refer to both of those.
(Catalina was before Big Sur.)
> Changelog: Catalina → Monterey

- Quicksilver/Code-App/QSPlugInsPrefPane.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-App/QSUpdateController.m
- Quicksilver/Code-QuickStepCore/QSPlugInManager.h
- Quicksilver/Code-QuickStepCore/QSPlugInManager.m
* Fixes a crash where some NSView updates were done on the background thread
* Removes a lot of the NSNotification calling
* Reduces/removes some obsolete code
The code changes look pretty big and scary, but ultimately all I did was:
Switched to using the new async `NSURLSession` instead of the synchronous `NSURLConnection` to make HTTP requests. This in turn meant that I had to pass `completionHandler` blocks around to know what to do once the request had completed.
The plugin code is really messy/complicated. I tried to tidy it up and remove calls to delegates etc. - blocks are much cleaner
> Update plugin updater to use blocks and better background thread management

- Quicksilver/Code-App/QSController.h
- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSDonationController.h
- Quicksilver/Code-App/QSDonationController.m
- Quicksilver/Code-QuickStepCore/QSPaths.h
- Quicksilver/Nibs/MainMenu.xib
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
1. Adds donation links to the main QS menu, and to the menu bar icon
2. Adds a donation alert, which opens on Quicksilver startup
The donation alert appears for any of the following:
* User upgraded Quicksilver
* User hasn't seen the alert for 1 week
The alert will be suppressed for the following:
* It's the first time the user's launched Quicksilver (we don't want to bother them if they're trying out Quicksilver for the first time)
* The user checked 'Do not show again for this version', and they haven't just upgraded
* For devs who've set a hidden pref (see here)
The only point worth making is that I guess a lot of users (like myself) only shut down their Macs every 2-3 weeks or months. That which means QS is only launched every 2-3 weeks or months, so the donation alert won't appear …
> Make donation links more prominent + add alert

- Quicksilver/PlugIns-Main/PrimerInterface/Primer.xib
- Quicksilver/PlugIns-Main/PrimerInterface/QSPrimerInterfaceController.h
- Quicksilver/PlugIns-Main/PrimerInterface/QSPrimerInterfaceController.m
Fixes #2695
Note that this is also explicitly disables using custom colours for the Primer interface. It was already pretty messy before: you could only change the window background colour, and that was done by setting the "Result Headers" background colour. Strange.
I figured since Primer is a... 'primer' interface, then hard-coding colours is preferable.
> Update Primer interface for dark mode

- Quicksilver/Code-App/QSTaskViewer.m
- Quicksilver/Code-QuickStepCore/QSLibrarian.h
- Quicksilver/Code-QuickStepCore/QSLibrarian.m
- Quicksilver/Code-QuickStepCore/QSTask.m
- Quicksilver/Code-QuickStepCore/QSTaskController.m
Fixes #2661
This is a simpler fix than I thought (I hope...)
It turns out we're already running scans on a background thread. See `QSCatalogEntry.m` at `- (NSArray *)scanAndCache;`
A further look at the spindumps in #2681 showed that the specific problem is with QSTask, and locking on showing/hiding tasks:
Main Thread:
```
1000  __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12 (CoreFoundation + 479292) [0x7ff81a95203c]
1000  -[QSLibrarian reloadSource:] + 562 (QSCore + 92849) [0x106e8eab1]
1000  -[QSTask stop] + 24 (QSCore + 314328) [0x106ec4bd8]
1000  objc_sync_enter + 27 (libobjc.A.dylib + 74862) [0x7ff81a73146e]
1000  __ulock_wait + 10 (libsystem_kernel.dylib + 12522)
```
2nd thread:
```
1000  __42-[QSLibrarian scanCatalogIgnoringIndexes:]_block_invoke + 649 (QSCore + …
```
> Make QSTask main thread calls async

- Quicksilver/Code-External/NSImageQuickLook/NSImage+QuickLook.m
- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
- Quicksilver/Code-QuickStepCore/QSTriggerCenter.m
- Quicksilver/Code-QuickStepFoundation/QSUTI.m
It helps having a 10 year old Mac ;-) I wouldn't say QS is 'slow', but it could definitely be snappier.
These changes are based on profiling using Instruments. Overall searching should be slightly faster, displaying action should be faster.
I propose this *isn't* merged into 2.0.0, but saved for a later release. We've got enough to work on right now.
> Performance tweaks

- Quicksilver/Code-App/QSModifierKeyEvents.h
- Quicksilver/Code-App/QSModifierKeyEvents.m
Replaced CGEventSourceSecondsSinceLastEventType by CGEventSourceCounterForEventType since the first seems to consider Fn up shortly after Fn down as key down event on BigSur.
Fixes #2533.
> Fix for #2533

- Quicksilver/Code-App/QSModifierKeyEvents.m
As mentioned in #2706, CapsLock as trigger did not work.
This PR fixes it, but due to the slow keys accessibility feature, using it requires good timing. I did not find an API call to query if slow keys is active for CapsLock (or the slow keys delay). Users that want to use double-CapsLock to trigger QS should probably turn of slow keys.
> Fixed handling of CapsLock as double modifier activation sequence.

- Quicksilver/Code-QuickStepCore/QSLibrarian.m
Fixes #2718
Very simple. Copy the dict before iterating over it to avoid any mutations during iteration.
> Copy over data dict when iterating

- Quicksilver/Code-QuickStepCore/QSProxyObject.m
- Quicksilver/Code-QuickStepCore/QSProxyObjectSource.m
Fixes #1660
Pretty simple fix. `QSProxyObject` (a subclass of QSBasicObject) override the `enabled` method, and did not call through to `super`.
> Fix enabling/disabling of proxy objects in catalog

- Quicksilver/Tools/travis/check_indent.rb
- README.markdown
There are a few other places that could be changed from `master` to
`main`, but they look mostly harmless to me.
The change to `check_indent.rb` may not actually be useful for anything:
https://github.com/quicksilver/Quicksilver/issues/2707#issuecomment-1094361203
But I've gone ahead and included it just in case.
Addresses https://github.com/quicksilver/Quicksilver/issues/2707
> Change the main branch reference in the main `README` to `main`.

- Quicksilver/Code-QuickStepCore/QSPlugIn.m
- Quicksilver/Code-QuickStepFoundation/NSBundle_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSBundle_BLTRExtensions.m
See also: https://github.com/quicksilver/Quicksilver/issues/2864
> Improve unsupported plugin architecture message

- .github/workflows/ci.yml
- Remove the key when we're done with it... just in case.
- This should upload a debug artifact with each release, yet to be tested.
> keep debug version

- .github/workflows/ci.yml
This branch was to help debug CI for https://github.com/quicksilver/Quicksilver/pull/2938#issuecomment-1694694593
> Debug uploading the debug artifact

- Quicksilver/Code-QuickStepCore/QSProcessMonitor.m
Fixes issue #2970
Note: This *re-introduces the bug fixed in #2917 - that bug is actually a Finder issue and not a QS issue
I thought I'd make a PR for this, so @skurfer @n8henrie can test. This should also fix #2975
Note that: this 'fix' re-introduces the bug fixed in #2917 - but upon further investigation, that is a Finder/macOS bug. The example used in the bug report was for Firefox. The example I found was for WeChat:
This .app bundle inside the main WeChat.app shows up as `WeChat` in Finder. However if you open the .app package and look at the Info.plist, the actual name should be `WeChatAppX` and the actual path in terminal is `WeChatAppX.app` not the supposed `WeChat.app` as shown in Finder:
This is a problem with macOS itself, more specifically the `NSURLLocalizedNameKey` resource …
> Don't override names for running processes

- Quicksilver/Code-App/QSApp.m
I think this is a reasonable move to automatically help people experiencing
show-stopper bugs on Sonoma.
The `Use Visual Effects` seems to even make first-time setup and installation
impossible on Sonoma in some cases; hopefully I put this early enough in
startup to catch these cases.
> Force-disable superfluous effects on startup

- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepFoundation/QSThreadSafeMutableDictionary.m
- **Simplify locks with @synchronized**
- **Use a threadsafe dict for data as well as cache**
> process monitor crashes

- .github/workflows/ci.yml
- Quicksilver/Code-App/QSController.m
- Quicksilver/Code-App/QSHelpersPrefPane.m
- Quicksilver/Code-App/QSMainPreferencePanes.m
- Quicksilver/Code-App/QSPreferencesController.m
- Quicksilver/Code-App/QSSetupAssistant.m
- Quicksilver/Code-QuickStepCore/QSCatalogEntry.m
- Quicksilver/Code-QuickStepCore/QSCatalogEntry_Private.h
- Quicksilver/Code-QuickStepCore/QSLibrarian.h
- Quicksilver/Code-QuickStepCore/QSObject.h
- Quicksilver/Code-QuickStepCore/QSObject.m
- Quicksilver/Code-QuickStepCore/QSObjectHandler.h
- Quicksilver/Code-QuickStepCore/QSObjectRanker.h
- Quicksilver/Code-QuickStepCore/QSObjectSource.h
- Quicksilver/Code-QuickStepCore/QSObject_Pasteboard.m
- Quicksilver/Code-QuickStepCore/QSPlugIn.m
- Quicksilver/Code-QuickStepCore/QSProcessMonitor.h
- Quicksilver/Code-QuickStepCore/QSSwiftObj.swift
- Quicksilver/Code-QuickStepCore/QSTrigger.m
- Quicksilver/Code-QuickStepCore/QSTriggerCenter.m
- Quicksilver/Code-QuickStepFoundation/NSString_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/NSWorkspace_BLTRExtensions.h
- Quicksilver/Code-QuickStepFoundation/QSGCD.h
- Quicksilver/Code-QuickStepInterface/QSDockingWindow.h
- Quicksilver/Code-QuickStepInterface/QSResizingInterfaceController.h
- Quicksilver/Code-QuickStepInterface/QSSearchObjectView.m
- Quicksilver/Code-QuickStepInterface/QSTableView.h
- Quicksilver/PlugIns-Main/PrimerInterface/QSPrimerInterfaceController.m
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- **macos-12 runner is deprecated**
- **Remove complex macros, which break compilation with Swift**
- **Remove complex macros, which are incompatible with Swift**
- **Add missing imports**
- **Add blank swift file**
- **Use Swift 6.0**
- **Fix minimum version message and https URL**
- **Remove outdated version target**
- **Add bare minimum to run swift from objc**
- **Swift 6.0 not avail in GHA runners at this point (xcode 15), stick to swift 5 for now**
- **Remove dummy Swift code**
> Prepare QS to include Swift

- Quicksilver/Code-App/QSController.m
That's a strange one, since `CGPreflightScreenCaptureAccess` is explicitly listed as working on macos10.15+, but I've changed the implementation here slightly to use the `isXXX` methods, and then just use `isBigSur` instead of `isCatalina`.
> Only check for screenshot permissions on macos11+

- Quicksilver/Code-QuickStepCore/QSObject_FileHandling.m
Makes sure that right arrowing into apps shows the latest 'recent documents' every time.
Fixes #3036
> Reload recent documents (children) every time

- .github/workflows/ci.yml
- Quicksilver/Tools/qs-nuke
- Quicksilver/Tools/qsrelease
- Quicksilver/Tools/qssign
- remove sensitive files ASAP
- add traps to also ensure their removal if script fails (belt and
suspenders)
- add `--` to `rm` calls to avoid potential risks with hyphenated
filenames
> Minor CI tweaks

- Quicksilver/Code-QuickStepInterface/DefaultBindings.qskeys
> Fix default bindings command string order

- Quicksilver/Code-QuickStepInterface/QSObjectView.m
- Quicksilver/Localized/en.lproj/QSAdvancedPrefPane.strings
- Quicksilver/Quicksilver.xcodeproj/project.pbxproj
- Quicksilver/Resources/DefaultsMap.plist
> Close window on drop

- Quicksilver/Code-QuickStepCore/QSProcessMonitor.m
During long-running debug sessions my log fills up with
`No object found for process 0`.
I'm fairly confident that GetEventParameter(... kEventParamProcessID)
returning PSN of 0 refers to the current process (though having trouble
finding this in official Apple documentation).
This silences this log spam when running in debug mode.
Alternatively could map `0` to the Quicksilver PID when scanning for running
processes, but that would add a little overhead every time processes were
scanned and might be problematic if someone had multiple QS processes running
(for whatever reason).
> Silence unhelpful log when object not found for self
